[package]
name = "rust_ui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.21.1"
paste = "1.0.14"
once_cell = "1.18.0"